### ISSUE TITLE
TemperatureReader: name

### ISSUE THREAD

**Issue by myjeeed** [myjeeed/MakerWear#22]
I am calling this (https://www.sparkfun.com/products/9570) the TemperatureReader. What are your other suggested kid-friendly names?

We also do have a TemperatureSensor which actually senses ambient temperature levels (compared to the TemperatureReader which reads the temperature of an object), however, the TemperatureSensor is less responsive to changes in the temperature.

**Comment by jonfroehlich** [comment]
Right, one is like the ambient temperature and the other is like an instantaneous point temperature.

Difference between a thermometer and those IR digital temperature meter guns ([like this one](http://www.amazon.com/Infrared-Digital-Temperature-Meter-Pointer/dp/B008615LSQ)).

So, maybe: 'Ambient Temperature' and 'Instant Temperature' or, since ambient is a high-literacy word, could try 'Thermometer' and 'Instant Temperature' or 'Point Temperature'...

**Comment by myjeeed** [comment]
We compared the two modules, and the point sensor was much better than the ambient temperature sensor.
So we won't be using the ambient temperature sensor any more, and we will call this module (the point temperature) the **TemperatureSensor**.

**Comment by jonfroehlich** [comment]
Does this also read ambient temperature if I just sort of point it at open space?
