### ISSUE TITLE
Counter 

### ISSUE THREAD

**Issue by alexjiao125** [myjeeed/MakerWear#45]
The counter module worked perfectly on a breadboard. However when implemented in an actual module there was flickering on the output.  The gamma-corrected LED flickered on each first count but not after that, and for normal LEDs, there was slight flickering on several counts.

Also, turning off the power does not reset the memory inside the ATtiny so the count still stays where it was before the power was turned off.  It will continue outputting voltage based on this count even with no power.

**Comment by myjeeed** [comment]
Great, thanks for making this module and testing it with the new LED module.
This is probably not a problem of the Counter module, and needs to be fixed within the new gamma-corrected LED module.

Regarding cascading two Counter modules to see numbers above 0-9. We are able to change the code to detect _new counts_ based on the falling edge instead of rising edge.

**Comment by myjeeed** [comment]
This is how the cover will look like for this module. Any feedback on it?
![image](https://cloud.githubusercontent.com/assets/9346800/16424220/42361b4c-3d2d-11e6-8569-92f3c628d77b.png)

**Comment by myjeeed** [comment]
Which one do you like more?
![image](https://cloud.githubusercontent.com/assets/9346800/16428263/173be6da-3d3f-11e6-98e1-d64f554ffc8b.png)

**Comment by jonfroehlich** [comment]
I think higher numbers should be above rather than below. 

In other words, do this descending order:
N
.
.
2
1
0

Rather than:
0
1
2
.
.
.
N

So the transition shown in least significant digit is from 1 to 2. Does that make sense?

Other than that, I love it.

**Comment by jonfroehlich** [comment]
How much do we actually count to?

Just 9 right?

So I suppose the most literal icon would be one digit. 

However, ignoring this, I like 3 digits

**Comment by myjeeed** [comment]
I personally like the one with 2 digits more. What do you think about these:

![image](https://cloud.githubusercontent.com/assets/9346800/16814820/7b1ba3a8-4905-11e6-873a-dfe69671c302.png)

![image](https://cloud.githubusercontent.com/assets/9346800/16814844/93ff63dc-4905-11e6-9a4e-a5e99669bc2f.png)

**Comment by jonfroehlich** [comment]
I think two digits is fine. However, unlike Liang's initial design, your numbers are a bit screwed up--in two places. First, the '1' font is weird--it's too hard to tell that this is a 1 because it has this stray part (purple circles). Second, the 0 should be centered and there should be part of a 1 above and part of a 9 below (where the 9 part should be is circled in red).

![image](https://cloud.githubusercontent.com/assets/1621749/16815277/30689ca6-4907-11e6-9e4c-0cc965b48238.png)

**Comment by myjeeed** [comment]
Ok, fixed it:
![image](https://cloud.githubusercontent.com/assets/9346800/16819731/cc70d0dc-491b-11e6-93e4-0d0b147a4faa.png)

**Comment by jonfroehlich** [comment]
Better but I can tell 9 is not on bottom below 0 on most significant digit

**Comment by myjeeed** [comment]
yep, fixed :)
![image](https://cloud.githubusercontent.com/assets/9346800/16821473/8097254a-4924-11e6-87b8-acaded263508.png)

**Comment by jonfroehlich** [comment]
Perfect!
