### ISSUE TITLE
Number module gets hot

### ISSUE THREAD

**Issue by jmcpeak2** [myjeeed/MakerWear#49]
The number module gets noticeably warm when turned on. We might need resistors to limit the current going to the LEDs in the 7 segment display. However, this isn't a practical solution because it would be difficult to add 7 resistors to the PCB.

I don't think the module gets hot enough to be dangerous or melt, but I suspect running at a high temperatures will cause the 7 segment display to wear out faster.

**Comment by jmcpeak2** [comment]
Just measured the current draw for the number module to be around 250 mA! No wonder it is getting so hot

**Comment by jonfroehlich** [comment]
Are you sure we can't get 7 surface mount resistors on the PCB?

What's the 7-seg rated at for current draw?

250mA is also power inefficient. Remember, these are wearables, we want to
maximize power efficiency whenever possible (and I realize we have a long
way to go here, especially since the idle state takes up lots of power in
our current architecture).

Jon

On Thu, Jun 23, 2016 at 2:41 PM, jmcpeak2 notifications@github.com wrote:

> Just measured the current draw for the number module to be around 250 mA!
> No wonder it is getting so hot
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/myjeeed/MakerWear/issues/49#issuecomment-228145115,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABi-9T9Jbm_iPMoLjMNMbGGsfA9WWpdqks5qOtNhgaJpZM4I9GuV
> .

## 

Jon Froehlich
Assistant Professor
Computer Science
University of Maryland, College Park
http://www.cs.umd.edu/~jonf/
@jonfroehlich https://twitter.com/jonfroehlich - Twitter

**Comment by jmcpeak2** [comment]
7-seg has a peak forward current listed at 160 mA, so we are definitely too high.

@myjeeed  would know if we can fit all 7 surface mount resistors.

Even if we can not, we could at least put one resistor between the common cathode and ground. This would solve our current draw problem, but would cause the brightness of the display to change depending on how many of the LEDs are turned on. I think this is probably the best solution

**Comment by jonfroehlich** [comment]
@jmcpeak2: I agree with your solution idea. Let's check with @myjeeed about whether there is room for the 7 SM resistors.

**Comment by myjeeed** [comment]
On average we have this number of LEDs ON for different digits: (5 + 2 + 5 + 5 + 4 + 5 + 6 + 3 + 7+ 5)/10 = 4.7 So we should calculate the resistance based on this to make sure that we have a consistent brightness for most of the digits.
